export const ROLES = {
  ADMIN: "Admin",
  BASE_COMMANDER: "BaseCommander",
  LOGISTICS_OFFICER: "LogisticsOfficer",
};

export const PERMISSIONS = {
  PURCHASE: [ROLES.ADMIN, ROLES.LOGISTICS_OFFICER],
  TRANSFER: [ROLES.ADMIN, ROLES.BASE_COMMANDER, ROLES.LOGISTICS_OFFICER],
  ASSIGN: [ROLES.ADMIN, ROLES.BASE_COMMANDER],
  EXPEND: [ROLES.ADMIN, ROLES.BASE_COMMANDER],
  READ_ALL: [ROLES.ADMIN],
};
